[package]
name = "skel"
version = "0.1.1"
authors = ["chris <chrisrhayden@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tempfile = "3.1.0"
toml = "0.5.6"
serde = { version = "1.0.113", features = ["derive"] }
clap = { git = "https://github.com/clap-rs/clap/" }
liquid = "0.20.1"
