[package]
name = "skel"
version = "0.1.1"
authors = ["chris <chrisrhayden@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tempfile = "3.2.0"
toml = "0.5"
serde = { version = "1.0.120", features = ["derive"] }
clap = "2"
