# all file's/directory's will be made to the root level
# like /current/path/test_js_project/src

# the root path, basically the project name for configs as this will be taken ove
# on the cli if given
root = "test_js_project"

# make all directory's listed, wont skip even if just made by the programme so
# you could skip src if you make src/foo
dirs = [
    "src",
    "src/foo",
    "docs",
    "tests",
]

# all directory's in file list not root need to be added to dirs
files = [
    "src/main.js",
    "tests/test_main.js",
]

[template]
{name = "src/main.js", template = """function main() {
    console.log("hello world");
}

main();
"""}

# a build script that will be run by bash,
# `#!/usr/bin/env bash` will be added, just for now probably a bad idea
build = """
echo "would run -- yarn init -y -cwd {{root}}"
echo "would run -- yarn add -cwd {{root}} 'eslint'"
"""
