# all file's/directory's will be made to the root level
# with name test_js_project
# dir "src/foo" will turn in to /current/path/test_js_project/src/foo

# TODO: find out if the top level variables need to be first

# the root path, basically the project name for configs as this will be taken ove
# on the cli if given
name = "test_js_project"

# make all directory's listed, wont skip even if just made by the programme so
# you could skip src if you make src/foo
dirs = [
    "src",
    "src/foo",
    "docs",
    "tests",
]

# all directory's in file list not root need to be added to dirs
files = [
    "src/main.js",
    "tests/test_main.js",
]


# a build script that will be run by bash,
# `#!/usr/bin/env bash` will be added, just for now probably a bad idea
build = """
echo "would run -- yarn init -y -cwd {{root}}"
echo "would run -- yarn add -cwd {{root}} 'eslint'"
"""

[[templates]]
name = "src/main.js"
template = """function run() {
    return  true;
}

function main() {
    console.log("hello world");
}

main();

module.run = run;
"""

[[templates]]
name = "tests/test_main.js"
template= """const { run } = require('./main');

function test_main() {
    if (!run()) {
        console.log("its fucked");
    }
}

test_main();
"""
